### ISSUE TITLE
How to renew our subscription? 

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [1Password/1password-teams-open-source#142]
Hi dear friends,

Our team account previously approved is now frozen : tensorlayer.

Could you guide to the process to renew our subscription?

All the best,

Jonathan 

_Sent from my Galaxy S9+ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by oliverdunk** [comment]
Hey @DEKHTIARJonathan 👋 To quote the README (I admit it's a little buried):

> Your membership can be renewed each year if your project still meets the requirements. Email us at opensource@1password.com 30 days before your membership ends.

I'll keep an eye out for your email 😄

**Comment by DEKHTIARJonathan** [comment]
My bad I didn't see it. I'm sending the email immediately.
Thanks a lot
