### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by mjdunne044** [1Password/1password-teams-open-source#261]
https://start.1password.com/open/i?a=XH5FZ4J44FHVJOI7UOVZQ2GALM&v=osnah7u2gvyghahgdwy3hnxlbe&i=t66mvkzjnvk4rvas6jo42db254&h=my.1password.com

**Comment by oliverdunk** [comment]
Hi @mjdunne044, I'm not sure if you opened this intentionally. If you'd like to apply for the promotion, please follow the instructions in the README :)
