### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by justintime4tea** [1Password/1password-teams-open-source#28]
Is this suppose to be a code repo or just an advertisement?

**Comment by ethomson** [comment]
![c7f334d0-b359-4300-b4df-e472474a8d24](https://user-images.githubusercontent.com/1130014/38736327-97514972-3f23-11e8-81c5-3803528a958a.jpg)

**Comment by justintime4tea** [comment]
I had before posting this issue and must admit I was being a tad of an ass :)

The one part I missed was the re-application and continuation of your services for free. I thought it was just the first year and then now that we're integrated with your workflow, pay us!  This "got my goat" a bit but with the ability to continue using your services for free, provided the project is still eligible, and using this REPO to track/show projects using your service isn't so bad. 

All in all I feel a bit better about your use of GitHub to advertise your services. Still kind of strikes me as... improper and... I dunno, off putting somehow? Not sure exactly what turns me off by this but it has that... how do I put it? ... It has a "smell" just like "code smell" where I smell/feel something isn't right here.

Best of luck to you though!

**Comment by justintime4tea** [comment]
Whether it's a service for free or a service for payment it's still an advertisement. Being that something is free doesn't make incapable of being advertised. It's much better than what I thought though still has a "smell".

**Comment by roustem** [comment]
Thank you for clarifying, @justintime4tea!
