### ISSUE TITLE
Not company affiliated Open Source

### ISSUE THREAD

**Issue by cdhunt** [1Password/1password-teams-open-source#297]
Hi,

I'm working on a couple of OSS projects without sponsorship or support from any company. I would like to use a 1password account to run integration tests against `op`. I've recruited a volunteer to be the second admin on the account, but we won't necessarily be using a single mail domain (work email).

https://github.com/cdhunt/op-powershell
https://github.com/cdhunt/SecretManagement.1Password

Is there still a way I can utilize a 1password account for development and testing purposes?

**Comment by oliverdunk** [comment]
Hey @cdhunt - I've reached out the team behind `op` to see what the best course of action is here. I'll let you know as soon as I hear back!

**Comment by oliverdunk** [comment]
Hey again! I'm back already 😅

You're more than welcome to apply for an account as an open source project. While you can add a company domain, which allows people with your invite link to join the account directly, you should also be able to invite anyone else regardless of their email address. If you run in to any trouble I'd be happy to help.

Going to close this one out - I look forward to your MR! And let me know if you have any further questions.
