### ISSUE TITLE
Can't update to version 7.8.1

### ISSUE THREAD

**Issue by colourfreak** [1Password/1password-teams-open-source#332]
I am on Macbook and iMac and can't update to the latest 7.8.1 version.

<img width="381" alt="Screenshot 2021-05-01 at 10 15 19" src="https://user-images.githubusercontent.com/51817359/116775979-71595c80-aa66-11eb-8668-34392e0309b9.png">

**Comment by oliverdunk** [comment]
Hi @colourfreak, that's odd! Could you go ahead and email support@1password.com for me? This GitHub repo isn't the best place for this, but we'd definitely love to help :)
