### ISSUE TITLE
Paid contributors?

### ISSUE THREAD

**Issue by TomWFox** [1Password/1password-teams-open-source#343]
Hi,

I'm a Core Maintainer for the [Parse Platform](https://parseplatform.org).

I noticed in the README that you don't accept projects with paid support or paid contributors.

I just wanted to double check this as there are projects listed e.g. Babel which do have such things. I'm guessing they applied before they started paying contributors?

Thanks,
Tom

**Comment by oliverdunk** [comment]
Hi Tom,

Looking at the Parse site, your project is absolutely one we'd love to support. Please do open an application and I'll get the promotion applied for you!

Our README is arguably a little restrictive although having a simple set of rules for what we do and don't support is tough. What we really want to make sure is that the accounts are helping an open source project, and that open source isn't just being used as a way to get 1Password for free. The AgileBits example is a great one I think - even though we try to open source some of our work, it wouldn't make sense for a company like ours to apply here.

Hope that helps!

**Comment by TomWFox** [comment]
That makes sense, thanks Oliver!
