### ISSUE TITLE
want to create button in Readme file for sign up and clearing the spelling mistakes!

### ISSUE THREAD

**Issue by pallasivasai** [1Password/1password-teams-open-source#819]
for simplicity and when the other contributors look into this repo it looks good and some of the spelling mistakes and corrections! please assign this issue to me @jodyheavener

**Comment by jodyheavener** [comment]
Hi @pallasivasai, following up from your PR, I don't think this issue can be considered valid at this time. Applicants to the program are responsible for writing their own descriptions. If you notice a spelling error in our own documentation you may open an issue to detail it and we'll work with you to understand the scope. Thank you for your interest!
